on:
  push:
    branches:
     - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 8

    - uses: gradle/actions/setup-gradle@v4

    - name: Build
      run: gradle build

    - name: Obfuscate
      run: gradle proguard

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: client
        path: |
          build/libs/*

  deob-map:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 21

    - name: Generate deob mapping
      run: |
        cp ref/remap.toml deob.toml
        wget https://github.com/LostCityRS/Deobfuscator/releases/latest/download/Deobfuscator.jar
        java -jar Deobfuscator.jar

    - name: Upload mapping
      uses: actions/upload-artifact@v4
      with:
        name: deob-map
        path: |
          remap.txt
